import { z } from 'zod';

export const WikiEntitySchema = z.object({
  slug: z.string(),
  displayName: z.string(),
  aliases: z.array(z.string()),
  category: z.enum(['Tech', 'Business', 'Design']),
  relatedEntities: z.array(z.string()),
  wikidataId: z.string().optional(),
  parentEntity: z.string().optional(),
});

export type WikiEntity = z.infer<typeof WikiEntitySchema>;

export const wikiEntities: WikiEntity[] = [
  {
    slug: 'next-js',
    displayName: 'Next.js',
    aliases: ['NextJS', 'Next.js Framework'],
    category: 'Tech',
    relatedEntities: [
      'react-server-components',
      'vercel',
      'server-side-rendering',
      'sanity',
      'typescript',
      'incremental-static-regeneration',
      'static-site-generation',
      'server-actions',
      'headless-cms',
      'largest-contentful-paint',
      'interaction-to-next-paint',
      'cumulative-layout-shift',
      'json-ld',
      'faqpage-schema',
      'breadcrumblist-schema',
      'localbusiness-schema',
      'hreflang',
      'canonical-tag',
      'sitemap-xml',
      'markdown-mirroring',
      'llms-txt',
      'tailwind-css',
      'lenis-scroll',
      'react-three-fiber',
      'glsl-shaders',
      'webgl',
      'service-worker',
      'progressive-web-app',
      'edge-computing',
      'route-handlers',
      'api-routes',
      'middleware',
      'image-optimization',
      'font-subsetting',
    ],
  },
  {
    slug: 'react-server-components',
    displayName: 'React Server Components',
    aliases: ['RSC'],
    category: 'Tech',
    relatedEntities: ['next-js', 'server-actions', 'server-side-rendering', 'typescript'],
  },
  {
    slug: 'vercel',
    displayName: 'Vercel',
    aliases: ['Vercel Deployment'],
    category: 'Tech',
    relatedEntities: ['next-js', 'edge-computing', 'e-e-a-t'],
  },
  {
    slug: 'sanity',
    displayName: 'Sanity',
    aliases: ['Sanity CMS', 'Sanity.io'],
    category: 'Tech',
    relatedEntities: ['headless-cms', 'next-js', 'e-e-a-t'],
  },
  {
    slug: 'headless-cms',
    displayName: 'Headless CMS',
    aliases: ['Headless Content Management System'],
    category: 'Tech',
    relatedEntities: ['sanity', 'headless-stack', 'next-js'],
  },
  {
    slug: 'core-web-vitals',
    displayName: 'Core Web Vitals',
    aliases: ['CWV', 'Google Core Web Vitals'],
    category: 'Tech',
    relatedEntities: [
      'largest-contentful-paint',
      'interaction-to-next-paint',
      'cumulative-layout-shift',
      'image-optimization',
      'font-subsetting',
    ],
  },
  {
    slug: 'largest-contentful-paint',
    displayName: 'Largest Contentful Paint',
    aliases: ['LCP'],
    category: 'Tech',
    relatedEntities: ['core-web-vitals', 'next-js', 'e-e-a-t'],
  },
  {
    slug: 'interaction-to-next-paint',
    displayName: 'Interaction to Next Paint',
    aliases: ['INP'],
    category: 'Tech',
    relatedEntities: ['core-web-vitals', 'next-js', 'e-e-a-t'],
  },
  {
    slug: 'cumulative-layout-shift',
    displayName: 'Cumulative Layout Shift',
    aliases: ['CLS'],
    category: 'Tech',
    relatedEntities: ['core-web-vitals', 'next-js', 'e-e-a-t'],
  },
  {
    slug: 'json-ld',
    displayName: 'JSON-LD',
    aliases: ['JavaScript Object Notation for Linked Data'],
    category: 'Tech',
    relatedEntities: ['schema-org', 'next-js', 'e-e-a-t'],
  },
  {
    slug: 'schema-org',
    displayName: 'Schema.org',
    aliases: ['Schema Markup'],
    category: 'Tech',
    relatedEntities: ['json-ld', 'faqpage-schema', 'breadcrumblist-schema', 'localbusiness-schema'],
  },
  {
    slug: 'faqpage-schema',
    displayName: 'FAQPage Schema',
    aliases: ['FAQ Schema'],
    category: 'Tech',
    relatedEntities: ['schema-org', 'next-js', 'e-e-a-t'],
  },
  {
    slug: 'breadcrumblist-schema',
    displayName: 'BreadcrumbList Schema',
    aliases: ['Breadcrumb Schema'],
    category: 'Tech',
    relatedEntities: ['schema-org', 'next-js', 'e-e-a-t'],
  },
  {
    slug: 'localbusiness-schema',
    displayName: 'LocalBusiness Schema',
    aliases: ['Local Business Markup'],
    category: 'Tech',
    relatedEntities: ['schema-org', 'next-js', 'e-e-a-t'],
  },
  {
    slug: 'hreflang',
    displayName: 'hreflang',
    aliases: ['hreflang tag', 'multilingual seo'],
    category: 'Tech',
    relatedEntities: ['canonical-tag', 'next-js', 'e-e-a-t'],
  },
  {
    slug: 'canonical-tag',
    displayName: 'Canonical Tag',
    aliases: ['rel=canonical'],
    category: 'Tech',
    relatedEntities: ['hreflang', 'robots-txt', 'next-js'],
  },
  {
    slug: 'robots-txt',
    displayName: 'robots.txt',
    aliases: ['Robots Exclusion Standard'],
    category: 'Tech',
    relatedEntities: ['canonical-tag', 'sitemap-xml', 'crawl-budget'],
  },
  {
    slug: 'sitemap-xml',
    displayName: 'sitemap.xml',
    aliases: ['XML Sitemap'],
    category: 'Tech',
    relatedEntities: ['robots-txt', 'crawl-budget', 'next-js'],
  },
  {
    slug: 'e-e-a-t',
    displayName: 'E-E-A-T',
    aliases: ['Experience, Expertise, Authoritativeness, Trustworthiness'],
    category: 'Tech',
    relatedEntities: [
      'topical-authority',
      'domain-authority',
      'generative-engine-optimization',
      'vercel',
      'sanity',
      'largest-contentful-paint',
      'interaction-to-next-paint',
      'cumulative-layout-shift',
      'json-ld',
      'faqpage-schema',
      'breadcrumblist-schema',
      'localbusiness-schema',
      'hreflang',
      'typescript',
      'tailwind-css',
      'lenis-scroll',
      'service-worker',
      'incremental-static-regeneration',
      'server-side-rendering',
      'static-site-generation',
      'server-actions',
      'route-handlers',
      'api-routes',
      'middleware',
      'image-optimization',
      'font-subsetting',
      'retainer-modell',
      'extreme-ownership',
      'festpreis-garantie',
      'agentur-vs-freelancer',
      'projekt-roi',
      'customer-acquisition-cost',
      'outbound-marketing',
      'account-based-marketing',
      'conversion-rate-optimization',
      'digital-pr',
      'page-authority',
      'doorway-page',
      'neuro-design',
      'golden-ratio',
      'fibonacci-scale',
      'magnetic-ui',
      'preloader',
      'parallax-scroll',
      'custom-cursor',
      'glassmorphism',
      'anti-ai-look',
      'fwa',
      'dribbble',
      'behance',
      'live-region',
      'haptic-feedback',
    ],
  },
  {
    slug: 'generative-engine-optimization',
    displayName: 'Generative Engine Optimization',
    aliases: ['GEO', 'AI Search Optimization'],
    category: 'Tech',
    relatedEntities: ['e-e-a-t', 'markdown-mirroring', 'llms-txt'],
  },
  {
    slug: 'markdown-mirroring',
    displayName: 'Markdown Mirroring',
    aliases: ['MD Mirroring', 'MDX Export'],
    category: 'Tech',
    relatedEntities: ['generative-engine-optimization', 'llms-txt', 'next-js'],
  },
  {
    slug: 'llms-txt',
    displayName: 'llms.txt',
    aliases: ['llmstxt'],
    category: 'Tech',
    relatedEntities: ['markdown-mirroring', 'generative-engine-optimization', 'next-js'],
  },
  {
    slug: 'typescript',
    displayName: 'TypeScript',
    aliases: ['TS', 'Typed JavaScript'],
    category: 'Tech',
    relatedEntities: ['next-js', 'react-server-components', 'e-e-a-t'],
  },
  {
    slug: 'tailwind-css',
    displayName: 'Tailwind CSS',
    aliases: ['Tailwind'],
    category: 'Tech',
    relatedEntities: ['design-token', 'next-js', 'e-e-a-t'],
  },
  {
    slug: 'framer-motion',
    displayName: 'Framer Motion',
    aliases: ['Framer'],
    category: 'Tech',
    relatedEntities: ['cinematic-page-transition', 'micro-interaction', 'kinetic-typography'],
  },
  {
    slug: 'lenis-scroll',
    displayName: 'Lenis Scroll',
    aliases: ['Lenis', 'Smooth Scrolling'],
    category: 'Tech',
    relatedEntities: ['parallax-scroll', 'next-js', 'e-e-a-t'],
  },
  {
    slug: 'react-three-fiber',
    displayName: 'React Three Fiber',
    aliases: ['R3F'],
    category: 'Tech',
    relatedEntities: ['webgl', 'glsl-shaders', 'next-js'],
  },
  {
    slug: 'glsl-shaders',
    displayName: 'GLSL Shaders',
    aliases: ['Shaders', 'WebGL Shaders'],
    category: 'Tech',
    relatedEntities: ['react-three-fiber', 'webgl', 'next-js'],
  },
  {
    slug: 'webgl',
    displayName: 'WebGL',
    aliases: ['Web Graphics Library'],
    category: 'Tech',
    relatedEntities: ['react-three-fiber', 'glsl-shaders', 'next-js'],
  },
  {
    slug: 'service-worker',
    displayName: 'Service Worker',
    aliases: ['ServiceWorkers'],
    category: 'Tech',
    relatedEntities: ['progressive-web-app', 'next-js', 'e-e-a-t'],
  },
  {
    slug: 'progressive-web-app',
    displayName: 'Progressive Web App',
    aliases: ['PWA'],
    category: 'Tech',
    relatedEntities: ['service-worker', 'mobile-first', 'next-js'],
  },
  {
    slug: 'edge-computing',
    displayName: 'Edge Computing',
    aliases: ['Edge Runtime', 'Edge Functions'],
    category: 'Tech',
    relatedEntities: ['vercel', 'middleware', 'next-js'],
  },
  {
    slug: 'incremental-static-regeneration',
    displayName: 'Incremental Static Regeneration',
    aliases: ['ISR'],
    category: 'Tech',
    relatedEntities: ['next-js', 'static-site-generation', 'e-e-a-t'],
  },
  {
    slug: 'server-side-rendering',
    displayName: 'Server-Side Rendering',
    aliases: ['SSR'],
    category: 'Tech',
    relatedEntities: ['next-js', 'react-server-components', 'e-e-a-t'],
  },
  {
    slug: 'static-site-generation',
    displayName: 'Static Site Generation',
    aliases: ['SSG'],
    category: 'Tech',
    relatedEntities: ['incremental-static-regeneration', 'next-js', 'e-e-a-t'],
  },
  {
    slug: 'server-actions',
    displayName: 'Server Actions',
    aliases: ['React Server Actions'],
    category: 'Tech',
    relatedEntities: ['react-server-components', 'next-js', 'e-e-a-t'],
  },
  {
    slug: 'route-handlers',
    displayName: 'Route Handlers',
    aliases: ['Next.js Route Handlers'],
    category: 'Tech',
    relatedEntities: ['api-routes', 'next-js', 'e-e-a-t'],
  },
  {
    slug: 'api-routes',
    displayName: 'API Routes',
    aliases: ['Next.js API Routes'],
    category: 'Tech',
    relatedEntities: ['route-handlers', 'next-js', 'e-e-a-t'],
  },
  {
    slug: 'middleware',
    displayName: 'Middleware',
    aliases: ['Next.js Middleware'],
    category: 'Tech',
    relatedEntities: ['edge-computing', 'next-js', 'e-e-a-t'],
  },
  {
    slug: 'image-optimization',
    displayName: 'Image Optimization',
    aliases: ['Next/Image', 'WebP Optimization'],
    category: 'Tech',
    relatedEntities: ['core-web-vitals', 'next-js', 'e-e-a-t'],
  },
  {
    slug: 'font-subsetting',
    displayName: 'Font Subsetting',
    aliases: ['Next/Font', 'Web Font Optimization'],
    category: 'Tech',
    relatedEntities: ['core-web-vitals', 'next-js', 'e-e-a-t'],
  },
  {
    slug: 'productized-service',
    displayName: 'Productized Service',
    aliases: ['Productized Agency'],
    category: 'Business',
    relatedEntities: [
      'retainer-modell',
      'festpreis-garantie',
      'vendor-lock-in',
      'extreme-ownership',
      'zero-lock-in',
      'headless-stack',
      'agentur-vs-freelancer',
      'projekt-roi',
      'customer-lifetime-value',
      'customer-acquisition-cost',
      'lead-magnet',
      'outbound-marketing',
      'account-based-marketing',
      'conversion-rate-optimization',
      'buyer-journey',
      'long-tail-content',
      'skyscraper-technique',
      'digital-pr',
      'page-authority',
      'crawl-budget',
      'programmatic-seo',
      'doorway-page',
    ],
  },
  {
    slug: 'retainer-modell',
    displayName: 'Retainer-Modell',
    aliases: ['Retainer', 'Monthly Retainer'],
    category: 'Business',
    relatedEntities: ['productized-service', 'e-e-a-t', 'vendor-lock-in', 'festpreis-garantie'],
  },
  {
    slug: 'vendor-lock-in',
    displayName: 'Vendor Lock-In',
    aliases: ['Lock-In Effekt'],
    category: 'Business',
    relatedEntities: ['zero-lock-in', 'anti-agentur', 'productized-service', 'retainer-modell'],
  },
  {
    slug: 'extreme-ownership',
    displayName: 'Extreme Ownership',
    aliases: ['Accountability'],
    category: 'Business',
    relatedEntities: ['anti-agentur', 'productized-service', 'e-e-a-t'],
  },
  {
    slug: 'anti-agentur',
    displayName: 'Anti-Agentur',
    aliases: ['Anti-Agency'],
    category: 'Business',
    relatedEntities: ['vendor-lock-in', 'extreme-ownership', 'agentur-vs-freelancer'],
  },
  {
    slug: 'zero-lock-in',
    displayName: 'Zero Lock-In',
    aliases: ['No Lock-In'],
    category: 'Business',
    relatedEntities: ['vendor-lock-in', 'headless-stack', 'productized-service'],
  },
  {
    slug: 'festpreis-garantie',
    displayName: 'Festpreis-Garantie',
    aliases: ['Fixed Price', 'Festpreis'],
    category: 'Business',
    relatedEntities: ['productized-service', 'e-e-a-t', 'retainer-modell'],
  },
  {
    slug: 'headless-stack',
    displayName: 'Headless-Stack',
    aliases: ['Headless Architecture'],
    category: 'Business',
    relatedEntities: ['headless-cms', 'zero-lock-in', 'productized-service'],
  },
  {
    slug: 'agentur-vs-freelancer',
    displayName: 'Agentur vs Freelancer',
    aliases: ['Freelancer oder Agentur'],
    category: 'Business',
    relatedEntities: ['anti-agentur', 'productized-service', 'e-e-a-t'],
  },
  {
    slug: 'projekt-roi',
    displayName: 'Projekt-RoI',
    aliases: ['Return on Investment', 'Webdesign ROI'],
    category: 'Business',
    relatedEntities: ['customer-lifetime-value', 'productized-service', 'e-e-a-t'],
  },
  {
    slug: 'customer-lifetime-value',
    displayName: 'Customer Lifetime Value',
    aliases: ['CLV', 'CLTV'],
    category: 'Business',
    relatedEntities: ['projekt-roi', 'customer-acquisition-cost', 'productized-service'],
  },
  {
    slug: 'customer-acquisition-cost',
    displayName: 'Customer Acquisition Cost',
    aliases: ['CAC'],
    category: 'Business',
    relatedEntities: ['customer-lifetime-value', 'productized-service', 'e-e-a-t'],
  },
  {
    slug: 'lead-magnet',
    displayName: 'Lead Magnet',
    aliases: ['Whitepaper', 'Freebie'],
    category: 'Business',
    relatedEntities: ['sales-funnel', 'inbound-marketing', 'productized-service'],
  },
  {
    slug: 'sales-funnel',
    displayName: 'Sales Funnel',
    aliases: ['Marketing Funnel'],
    category: 'Business',
    relatedEntities: [
      'lead-magnet',
      'conversion-rate-optimization',
      'inbound-marketing',
      'buyer-journey',
    ],
  },
  {
    slug: 'inbound-marketing',
    displayName: 'Inbound Marketing',
    aliases: ['Inbound'],
    category: 'Business',
    relatedEntities: ['lead-magnet', 'sales-funnel', 'content-pillar', 'buyer-journey'],
  },
  {
    slug: 'outbound-marketing',
    displayName: 'Outbound Marketing',
    aliases: ['Outbound'],
    category: 'Business',
    relatedEntities: ['account-based-marketing', 'productized-service', 'e-e-a-t'],
  },
  {
    slug: 'account-based-marketing',
    displayName: 'Account-Based Marketing',
    aliases: ['ABM'],
    category: 'Business',
    relatedEntities: ['outbound-marketing', 'productized-service', 'e-e-a-t'],
  },
  {
    slug: 'conversion-rate-optimization',
    displayName: 'Conversion Rate Optimization',
    aliases: ['CRO', 'Conversion Optimierung'],
    category: 'Business',
    relatedEntities: ['sales-funnel', 'productized-service', 'e-e-a-t'],
  },
  {
    slug: 'buyer-journey',
    displayName: 'Buyer Journey',
    aliases: ['Customer Journey'],
    category: 'Business',
    relatedEntities: ['sales-funnel', 'inbound-marketing', 'productized-service'],
  },
  {
    slug: 'long-tail-content',
    displayName: 'Long-Tail Content',
    aliases: ['Long-Tail SEO'],
    category: 'Business',
    relatedEntities: ['topical-authority', 'programmatic-seo', 'productized-service'],
  },
  {
    slug: 'topical-authority',
    displayName: 'Topical Authority',
    aliases: ['Themenautorität'],
    category: 'Business',
    relatedEntities: ['e-e-a-t', 'long-tail-content', 'content-pillar'],
  },
  {
    slug: 'content-pillar',
    displayName: 'Content Pillar',
    aliases: ['Pillar Page', 'Hub Page'],
    category: 'Business',
    relatedEntities: ['inbound-marketing', 'topical-authority', 'skyscraper-technique'],
  },
  {
    slug: 'skyscraper-technique',
    displayName: 'Skyscraper Technique',
    aliases: ['Skyscraper SEO'],
    category: 'Business',
    relatedEntities: ['content-pillar', 'backlink-profile', 'productized-service'],
  },
  {
    slug: 'backlink-profile',
    displayName: 'Backlink Profile',
    aliases: ['Backlinks'],
    category: 'Business',
    relatedEntities: ['skyscraper-technique', 'digital-pr', 'domain-authority'],
  },
  {
    slug: 'digital-pr',
    displayName: 'Digital PR',
    aliases: ['Online PR'],
    category: 'Business',
    relatedEntities: ['backlink-profile', 'productized-service', 'e-e-a-t'],
  },
  {
    slug: 'domain-authority',
    displayName: 'Domain Authority',
    aliases: ['DA', 'Domain Rating'],
    category: 'Business',
    relatedEntities: ['e-e-a-t', 'backlink-profile', 'page-authority'],
  },
  {
    slug: 'page-authority',
    displayName: 'Page Authority',
    aliases: ['PA'],
    category: 'Business',
    relatedEntities: ['domain-authority', 'productized-service', 'e-e-a-t'],
  },
  {
    slug: 'crawl-budget',
    displayName: 'Crawl Budget',
    aliases: ['Googlebot Crawl Budget'],
    category: 'Business',
    relatedEntities: ['robots-txt', 'sitemap-xml', 'productized-service'],
  },
  {
    slug: 'programmatic-seo',
    displayName: 'Programmatic SEO',
    aliases: ['pSEO'],
    category: 'Business',
    relatedEntities: ['long-tail-content', 'doorway-page', 'productized-service'],
  },
  {
    slug: 'doorway-page',
    displayName: 'Doorway Page',
    aliases: ['Brückenseite'],
    category: 'Business',
    relatedEntities: ['programmatic-seo', 'productized-service', 'e-e-a-t'],
  },
  {
    slug: 'neuro-design',
    displayName: 'Neuro Design',
    aliases: ['Neurodesign', 'Psychological Design'],
    category: 'Design',
    relatedEntities: ['dark-mode-psychology', 'awwwards', 'e-e-a-t', 'fwa'],
  },
  {
    slug: 'golden-ratio',
    displayName: 'Golden Ratio',
    aliases: ['Goldener Schnitt'],
    category: 'Design',
    relatedEntities: ['fibonacci-scale', 'awwwards', 'e-e-a-t'],
  },
  {
    slug: 'fibonacci-scale',
    displayName: 'Fibonacci Scale',
    aliases: ['Fibonacci Grid'],
    category: 'Design',
    relatedEntities: ['golden-ratio', 'awwwards', 'e-e-a-t'],
  },
  {
    slug: '60-30-10-color-rule',
    displayName: '60-30-10 Color Rule',
    aliases: ['60-30-10 Rule', 'Color Proportion Rule'],
    category: 'Design',
    relatedEntities: ['color-contrast-ratio', 'design-token', 'awwwards'],
  },
  {
    slug: 'wcag-aaa',
    displayName: 'WCAG AAA',
    aliases: ['Web Content Accessibility Guidelines', 'Barrierefreiheit'],
    category: 'Design',
    relatedEntities: [
      'color-contrast-ratio',
      'prefers-reduced-motion',
      'aria-role',
      'touch-target',
      'focus-ring',
      'skip-link',
    ],
  },
  {
    slug: 'prefers-reduced-motion',
    displayName: 'prefers-reduced-motion',
    aliases: ['Reduced Motion'],
    category: 'Design',
    relatedEntities: ['wcag-aaa', 'kinetic-typography', 'awwwards'],
  },
  {
    slug: 'kinetic-typography',
    displayName: 'Kinetic Typography',
    aliases: ['Animated Typography'],
    category: 'Design',
    relatedEntities: ['prefers-reduced-motion', 'framer-motion', 'awwwards'],
  },
  {
    slug: 'magnetic-ui',
    displayName: 'Magnetic UI',
    aliases: ['Magnetic Buttons'],
    category: 'Design',
    relatedEntities: ['micro-interaction', 'awwwards', 'e-e-a-t'],
  },
  {
    slug: 'cinematic-page-transition',
    displayName: 'Cinematic Page Transition',
    aliases: ['Page Transitions'],
    category: 'Design',
    relatedEntities: ['framer-motion', 'preloader', 'awwwards'],
  },
  {
    slug: 'preloader',
    displayName: 'Preloader',
    aliases: ['Loading Screen'],
    category: 'Design',
    relatedEntities: ['cinematic-page-transition', 'awwwards', 'e-e-a-t'],
  },
  {
    slug: 'parallax-scroll',
    displayName: 'Parallax Scroll',
    aliases: ['Parallax'],
    category: 'Design',
    relatedEntities: ['lenis-scroll', 'awwwards', 'e-e-a-t'],
  },
  {
    slug: 'mix-blend-mode',
    displayName: 'Mix Blend Mode',
    aliases: ['CSS Blend Modes'],
    category: 'Design',
    relatedEntities: ['dark-mode-psychology', 'glassmorphism', 'awwwards'],
  },
  {
    slug: 'custom-cursor',
    displayName: 'Custom Cursor',
    aliases: ['Cursor Effects'],
    category: 'Design',
    relatedEntities: ['micro-interaction', 'awwwards', 'e-e-a-t'],
  },
  {
    slug: 'glassmorphism',
    displayName: 'Glassmorphism',
    aliases: ['Frosted Glass Effect'],
    category: 'Design',
    relatedEntities: ['mix-blend-mode', 'awwwards', 'e-e-a-t'],
  },
  {
    slug: 'dark-mode-psychology',
    displayName: 'Dark Mode Psychology',
    aliases: ['Dark Theme Psychology'],
    category: 'Design',
    relatedEntities: ['neuro-design', 'mix-blend-mode', 'anti-ai-look'],
  },
  {
    slug: 'anti-ai-look',
    displayName: 'Anti-AI Look',
    aliases: ['Human Design'],
    category: 'Design',
    relatedEntities: ['dark-mode-psychology', 'awwwards', 'e-e-a-t'],
  },
  {
    slug: 'awwwards',
    displayName: 'Awwwards',
    aliases: ['Awwwards Standard'],
    category: 'Design',
    relatedEntities: [
      'fwa',
      'dribbble',
      'neuro-design',
      'golden-ratio',
      'fibonacci-scale',
      '60-30-10-color-rule',
      'prefers-reduced-motion',
      'kinetic-typography',
      'magnetic-ui',
      'cinematic-page-transition',
      'preloader',
      'parallax-scroll',
      'mix-blend-mode',
      'custom-cursor',
      'glassmorphism',
      'anti-ai-look',
      'behance',
      'mobile-first',
      'touch-target',
      'focus-ring',
      'skip-link',
      'aria-role',
      'live-region',
      'color-contrast-ratio',
      'haptic-feedback',
      'design-token',
    ],
  },
  {
    slug: 'fwa',
    displayName: 'FWA',
    aliases: ['Favourite Website Awards'],
    category: 'Design',
    relatedEntities: ['awwwards', 'e-e-a-t', 'neuro-design'],
  },
  {
    slug: 'dribbble',
    displayName: 'Dribbble',
    aliases: ['Dribbble Design'],
    category: 'Design',
    relatedEntities: ['awwwards', 'behance', 'e-e-a-t'],
  },
  {
    slug: 'behance',
    displayName: 'Behance',
    aliases: ['Behance Portfolio'],
    category: 'Design',
    relatedEntities: ['dribbble', 'awwwards', 'e-e-a-t'],
  },
  {
    slug: 'mobile-first',
    displayName: 'Mobile-First',
    aliases: ['Mobile Design'],
    category: 'Design',
    relatedEntities: ['progressive-web-app', 'touch-target', 'awwwards'],
  },
  {
    slug: 'touch-target',
    displayName: 'Touch Target',
    aliases: ['Tap Target', 'Touch Area'],
    category: 'Design',
    relatedEntities: ['mobile-first', 'wcag-aaa', 'awwwards'],
  },
  {
    slug: 'focus-ring',
    displayName: 'Focus Ring',
    aliases: ['CSS Focus'],
    category: 'Design',
    relatedEntities: ['wcag-aaa', 'skip-link', 'awwwards'],
  },
  {
    slug: 'skip-link',
    displayName: 'Skip Link',
    aliases: ['Skip to content'],
    category: 'Design',
    relatedEntities: ['focus-ring', 'wcag-aaa', 'awwwards'],
  },
  {
    slug: 'aria-role',
    displayName: 'ARIA Role',
    aliases: ['WAI-ARIA'],
    category: 'Design',
    relatedEntities: ['wcag-aaa', 'live-region', 'awwwards'],
  },
  {
    slug: 'live-region',
    displayName: 'Live Region',
    aliases: ['ARIA Live'],
    category: 'Design',
    relatedEntities: ['aria-role', 'awwwards', 'e-e-a-t'],
  },
  {
    slug: 'color-contrast-ratio',
    displayName: 'Color Contrast Ratio',
    aliases: ['Kontrastverhältnis'],
    category: 'Design',
    relatedEntities: ['60-30-10-color-rule', 'wcag-aaa', 'awwwards'],
  },
  {
    slug: 'haptic-feedback',
    displayName: 'Haptic Feedback',
    aliases: ['Haptics', 'Vibration API'],
    category: 'Design',
    relatedEntities: ['micro-interaction', 'awwwards', 'e-e-a-t'],
  },
  {
    slug: 'micro-interaction',
    displayName: 'Micro Interaction',
    aliases: ['Microinteractions'],
    category: 'Design',
    relatedEntities: ['framer-motion', 'magnetic-ui', 'custom-cursor', 'haptic-feedback'],
  },
  {
    slug: 'design-token',
    displayName: 'Design Token',
    aliases: ['Design System Tokens'],
    category: 'Design',
    relatedEntities: ['tailwind-css', '60-30-10-color-rule', 'awwwards'],
  },
];

export const getWikiEntityBySlug = (slug: string): WikiEntity | undefined => {
  return wikiEntities.find((e) => e.slug === slug);
};

export const getWikiEntitiesByCategory = (category: string): WikiEntity[] => {
  return wikiEntities.filter((e) => e.category === category);
};
